HairSalon/Models/Client.cs
using System.Collections.Generic;
using MySql.Data.MySqlClient;

namespace HairSalon.Models
{
    public class Client
    {
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public int StylistId { get; set; }

        public virtual Stylist Stylist { get; set; }
    }
}

HairSalon/Models/HairSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
    public class HairSalonContext : DbContext
    {
        public virtual DbSet<Stylist> Stylists { get; set; }
        public DbSet<Client> Clients { get; set; }

        public HairSalonContext(DbContextOptions options) : base(options) { }
    }
}

HairSalon/Models/ModelsContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
    public class HairSalonContext : DbContext
    {
        public DbSet<Client> Clients { get; set; }

        public HairSalonContext(DbContextOptions options) : base(options) { }
    }
}

HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
    public class Stylist
    {
        public Stylist()
        {
            this.Clients = new HashSet<Client>();
        }
        public int StylistId { get; set; }

        public string StylistName { get; set; }

        public virtual ICollection<Client> Clients { get; set; }
    }
}
        

HairSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HairSalon.Controllers
{
    public class ClientsController : Controller
    {
        private readonly HairSalonContext _db;
        public ClientsController(HairSalonContext db)
        {
            _db = db;
        }
        public ActionResult Index()
        {
            List<Client> model = _db.Clients.Include(clients => clients.Stylist).ToList();
            return View(model);
        }
        public ActionResult Create()
        {
            ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "StylistName");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Client client)
        {
            _db.Clients.Add(client);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id)
        {
            var thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
            ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "StylistName");
            return View(thisClient);
        }

        [HttpPost]
        public ActionResult Edit(Client client)
        {
            _db.Entry(client).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            var thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
            return View(thisClient);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
            _db.Clients.Remove(thisClient);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HairSalon.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet("/")]
        public ActionResult Index()
        {
            return View();
        }
    }
}

HairSalon/Controllers/StylistsController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Controllers
{
    public class StylistsController : Controller
    {
        private readonly HairSalonContext _db;

        public StylistsController(HairSalonContext db)
        {
            _db = db;
        }
        public ActionResult Index()
        {
            List<Stylist> model = _db.Stylists.ToList();
            return View(model);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Stylist stylist)
        {
            _db.Stylists.Add(stylist);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Details(int id)
        {
            Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
            return View(thisStylist);
        }
    }
}

HairSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h4>Add a new client</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.ClientName)
    @Html.TextBoxFor(model => model.ClientName)

    @Html.LabelFor(model => model.Stylist)
    @Html.DropDownList("StylistId")

    <input type="submit" value="Add new client" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all clients", "Index")</p>

HairSalon/Views/Clients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Are you sure you want to delete this client? Maybe offer them a new stylist?</h2>

@Html.DisplayNameFor(model => model.ClientName): @Html.DisplayFor(model => model.ClientName)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" class="btn btn-default"/>
}
@Html.ActionLink("Back to client list", "Index")

HairSalon/Views/Clients/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Client Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.ClientName): @Html.DisplayFor(model => model.ClientName)<h3>
<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit client", "Edit", new { id = Model.ClientId })</p>
<p>@Html.ActionLink("Delete client", "Delete", new { id = Model.ClientId })</p>

HairSalon/Views/Clients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Edit</h2>

<h4>Edit this client: @Html.DisplayFor(model => model.ClientName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ClientId)

    @Html.LabelFor(model => model.ClientName)
    @Html.EditorFor(model => model.ClientName)

    @Html.LabelFor(model => model.Stylist)
    @Html.DropDownList("StylistId")

    <input type="submit" value="Save" class="btn btn-default"/>
}

<p>@Html.ActionLink("Back to client list", "Index")</p>

HairSalon/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Client>;

<h1>Clients</h1>

@if (@Model.Count == 0)
{
  <h3>No clients have been added yet! Better get on that, Claire.</h3>
} 

@foreach (Client client in Model)
{
  <li>@Html.ActionLink($"{client.ClientName}", "Details", new { id = client.ClientId }) | @client.Stylist.StylistName</li>
}

<p>@Html.ActionLink("Add new client", "Create")</p>
<p>@Html.ActionLink("See all stylists", "Index", "Stylists")</p>

HairSalon/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Hello Claire. Welcome to your stylist and client database.</h1>

<p>@Html.ActionLink("See all clients", "Index", "Clients")</p> 
<p>@Html.ActionLink("Add new client", "Create", "Clients")</p>
<p>@Html.ActionLink("See all stylists", "Index", "Stylists")</p>
<p>@Html.ActionLink("Add new stylist", "Create", "Stylists")</p>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hair Salon Manager</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>

HairSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h4>Add a new stylist</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.StylistName)
    @Html.TextBoxFor(model => model.StylistName)
    <input type="submit" value="Add new stylist" class="btn btn-dark"/>
}
<p>@Html.ActionLink("See all stylists", "Index", "Stylists")</p>

HairSalon/Views/Stylists/Details.cshtml
@using HairSalon.Models;

@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h2>Stylist Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.StylistName): @Html.DisplayFor(model => model.StylistName)</h3>


@if (@Model.Clients.Count == 0)
{
  <p>no clients yet</p>
}

@foreach (Client client in @Model.Clients)
{
  <li>Client: @client.ClientName</li>
}
</ul>


<p>@Html.ActionLink("Add new stylist", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Stylist>;

<h1>Stylists</h1>

<ul>
  @foreach(Stylist stylist in Model)
  {
      <li>@Html.ActionLink($"{stylist.StylistName}", "Details", new { id = stylist.StylistId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new stylist", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>